name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - ankit_logger_changes
      - logger_changes
      - main

# Define environment variables
env:
  PROJECT_ID: probestack-e2068
  SERVICE_ACCOUNT_EMAIL: github-actions-deployer@probestack-e2068.iam.gserviceaccount.com
  SERVICE_NAME: migrationx-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Setup the gcloud CLI environment (Useful for running gcloud commands)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Authenticate Docker to push images to GCR/Artifact Registry
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: '${{ secrets.GCP_SA_KEY }}'

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          # Use GITHUB_SHA as a unique tag for the image
          IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy the container to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
